import React from 'react';
import './App.styl';

const App = () => {
  return (
    <>
      <p>
        <code>It works!</code>
      </p>
      <p>Generated by <code>dollie.js</code></p>
    </>
  );
};

export default App;
