import React from 'react';
import './App.css';
import { connect } from 'react-redux';
import { Dispatch, AnyAction } from 'redux';
import { AppState, increaseCount, decreaseCount } from './store/models/app';
import { State } from './store';

export interface AppProps extends AppState {
  dispatch: Dispatch<AnyAction>;
  state: State;
  increaseCount: () => void;
  decreaseCount: () => void;
}

const mapStateToProps = (state: State) => {
  return { state };
};

const mapDispatchToProps = (dispatch: Dispatch) => {
  return {
    increaseCount: () => {
      dispatch(increaseCount());
    },
    decreaseCount: () => {
      dispatch(decreaseCount());
    },
  };
};

const App: React.FC<AppProps> = (props) => {
  return (
    <>
      <p>
        <code>It works!</code>
      </p>
      <p>Generated by <code>dollie.js</code></p>
      <div>
        <button onClick={props.increaseCount}>+</button>
        <code>{props.state.app.count}</code>
        <button onClick={props.decreaseCount}>-</button>
      </div>
    </>
  );
};

export default connect(mapStateToProps, mapDispatchToProps)(App);
