import React from 'react';
import './App.css';
import { connect } from 'react-redux';
import { increaseCount, decreaseCount } from './store/models/app';

const mapStateToProps = (state) => {
  return { state };
};

const mapDispatchToProps = (dispatch) => {
  return {
    increaseCount: () => {
      dispatch(increaseCount());
    },
    decreaseCount: () => {
      dispatch(decreaseCount());
    },
  };
};

const App = (props) => {
  return (
    <>
      <p>
        <code>It works!</code>
      </p>
      <p>Generated by <code>dollie.js</code></p>
      <div>
        <button onClick={props.increaseCount}>+</button>
        <code>{props.state.app.count}</code>
        <button onClick={props.decreaseCount}>-</button>
      </div>
    </>
  );
};

export default connect(mapStateToProps, mapDispatchToProps)(App);
