import React from 'react';
import { connect } from './patches/dva';
import './App.css';

const App = (props) => {
  return (
    <>
      <p>
        <code>It works!</code>
      </p>
      <p>Generated by <code>dollie.js</code></p>
      <div>
        <button
          onClick={() => {
            props.dispatch({
              type: 'app/increaseCount',
            });
          }}
        >+</button>
        <code>{props.count}</code>
        <button
          onClick={() => {
            props.dispatch({
              type: 'app/decreaseCount',
            });
          }}
        >-</button>
      </div>
    </>
  );
};

export default connect(({ app }) => app)(App);
