import React from 'react';
import { connect } from './patches/dva';
import { ConnectState } from './models';
import { AppState } from './models/app';
import { Dispatch, AnyAction } from 'redux';
import './App.css';

export interface AppProps extends AppState {
  dispatch: Dispatch<AnyAction>;
}

const App: React.FC<AppProps> = (props) => {
  return (
    <>
      <p>
        <code>It works!</code>
      </p>
      <p>Generated by <code>dollie.js</code></p>
      <div>
        <button
          onClick={() => {
            props.dispatch({
              type: 'app/increaseCount',
            });
          }}
        >+</button>
        <code>{props.count}</code>
        <button
          onClick={() => {
            props.dispatch({
              type: 'app/decreaseCount',
            });
          }}
        >-</button>
      </div>
    </>
  );
};

export default connect(({ app }: ConnectState) => app)(App);
